# Generated by Django 5.2.6 on 2025-09-26 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TouristRoute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название маршрута')),
                ('description', models.TextField(verbose_name='Описание')),
                ('length_km', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Протяженность (км)')),
                ('duration_days', models.PositiveIntegerField(verbose_name='Продолжительность (дней)')),
                ('difficulty', models.CharField(choices=[('легкий', 'Легкий'), ('средний', 'Средний'), ('сложный', 'Сложный')], max_length=10, verbose_name='Сложность')),
                ('region', models.CharField(max_length=100, verbose_name='Регион')),
                ('best_season', models.CharField(max_length=100, verbose_name='Лучшее время для похода')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
