# Generated by Django 5.2.6 on 2025-10-03 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routes_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='touristroute',
            name='guide_required',
            field=models.BooleanField(default=False, verbose_name='Требуется гид'),
        ),
        migrations.AlterField(
            model_name='touristroute',
            name='best_season',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Лучшее время для похода'),
        ),
    ]
