# Generated by Django 5.2.6 on 2025-10-03 06:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('routes_app', '0002_touristroute_guide_required_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='touristroute',
            name='guide_required',
        ),
    ]
