# Generated by Django 5.2.6 on 2025-10-10 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routes_app', '0003_remove_touristroute_guide_required'),
    ]

    operations = [
        migrations.AddField(
            model_name='touristroute',
            name='kolvo_chel',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Количество человек'),
        ),
    ]
