# Generated by Django 5.2.7 on 2025-10-27 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routes_app', '0004_touristroute_kolvo_chel'),
    ]

    operations = [
        migrations.AddField(
            model_name='touristroute',
            name='source',
            field=models.CharField(choices=[('db', 'База данных'), ('xml', 'XML файл')], default='db', max_length=10, verbose_name='Источник данных'),
        ),
        migrations.AlterUniqueTogether(
            name='touristroute',
            unique_together={('name', 'region', 'length_km')},
        ),
    ]
