"""
Django settings for tourist_routes project.

Generated by 'django-admin startproject' using Django 5.2.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""
import os
from pathlib import Path
import sys
try:
    # Optional import: if `python-dotenv` isn't installed we should still
    # allow Django to load (e.g., in minimal environments). Wrap import
    # so `manage.py` commands don't fail with ModuleNotFoundError.
    from dotenv import load_dotenv  # type: ignore
except ImportError:
    load_dotenv = None

# Load environment variables from `.env` if python-dotenv is available.
if load_dotenv:
    try:
        load_dotenv()
    except Exception:
        # Ignore any errors reading the .env file; environment may be
        # provided by the environment (e.g., Docker, CI).
        pass

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('SECRET_KEY', 'django-insecure-#n4oi-6vg$+fr=zrh(1^7-apern3r2t%f#jhhj(c$t#d1a2czk')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('DEBUG', 'False') == 'True'

ALLOWED_HOSTS = os.getenv('ALLOWED_HOSTS', 'localhost,127.0.0.1,0.0.0.0').split(',')


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'routes_app',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'tourist_routes.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'tourist_routes.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# Use PostgreSQL in production, SQLite for local development
DB_ENGINE = os.getenv('DB_ENGINE', 'django.db.backends.sqlite3')
DB_NAME = os.getenv('DB_NAME', str(BASE_DIR / 'db.sqlite3'))
DB_USER = os.getenv('DB_USER', '')
DB_PASSWORD = os.getenv('DB_PASSWORD', '')
DB_HOST = os.getenv('DB_HOST', '')
DB_PORT = os.getenv('DB_PORT', '')


def _is_valid_postgres_config():
    """Return True when the minimal Postgres env vars look sane.

    This tries to catch malformed or non-text values coming from a bad
    `.env` encoding or accidental binary data. If validation fails we
    fall back to SQLite to avoid crashing `runserver` during local
    development.
    """
    try:
        # Basic presence check
        for v in (DB_NAME, DB_USER, DB_PASSWORD, DB_HOST):
            if not v or not isinstance(v, str):
                return False
            # ensure it can be encoded to UTF-8 and contains no C0 control chars
            v.encode('utf-8')
            import re

            if re.search(r'[\x00-\x08\x0b\x0c\x0e-\x1f]', v):
                return False
        return True
    except Exception:
        return False


USE_POSTGRES = os.getenv('USE_POSTGRES', 'False') == 'True'

# Detect when Django is started via `runserver` so we can avoid attempting
# to connect to an external Postgres during quick local development runs.
IS_RUNSERVER = any('runserver' in a for a in sys.argv)

# Only enable PostgreSQL when explicitly requested via USE_POSTGRES or when
# running in non-debug (production) mode and the config looks valid. This
# prevents accidental attempts to connect to a malformed Postgres config
# during local development (`runserver`).
if (
    DB_ENGINE == 'django.db.backends.postgresql'
    and _is_valid_postgres_config()
    and (USE_POSTGRES or not DEBUG)
    and (not IS_RUNSERVER or USE_POSTGRES)
):
    DATABASES = {
        'default': {
            'ENGINE': DB_ENGINE,
            'NAME': DB_NAME,
            'USER': DB_USER,
            'PASSWORD': DB_PASSWORD,
            'HOST': DB_HOST,
            'PORT': DB_PORT,
            'CONN_MAX_AGE': 600,
            'ATOMIC_REQUESTS': True,
        }
    }
else:
    # If the environment suggests PostgreSQL but the values look invalid,
    # fall back to the local SQLite DB for developer convenience.
    if DB_ENGINE == 'django.db.backends.postgresql':
        try:
            import warnings

            warnings.warn(
                'Postgres configuration appears invalid or contains non-text values; '
                'falling back to SQLite for local development.'
            )
        except Exception:
            pass

    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'ru-ru'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

MEDIA_URL = '/media/'

MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
